trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- checkout: self

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'my-service-connection-practice'
    appType: 'webApp'
    appName: 'web-app-practice'
    package: '$(System.DefaultWorkingDirectory)'
